MicropostMVC/Controllers/MicropostsController.cs
using System.Web.Mvc;
using MicropostMVC.BusinessServices;
using MicropostMVC.Framework.Common;
using MicropostMVC.Models;

namespace MicropostMVC.Controllers
{
    public class MicropostsController : Controller
    {
        private readonly IUserBS _userBS;
        private readonly IMicropostBS _micropostBS;

        public MicropostsController(IUserBS userBS, IMicropostBS micropostBS)
        {
            _userBS = userBS;
            _micropostBS = micropostBS;
        }

        public ActionResult Index()
        {
            UserModel loggedUser = GetUserModelForAuthenticatedUser();
            MicropostsForUserModel micropostsForUser = _micropostBS.GetMicropostsForUser(loggedUser);
            return View(micropostsForUser);
        }

        [HttpPost]
        public ActionResult Create()
        {
            string content = Request.Params["micropostNew"];
            
            bool isEmpty = string.IsNullOrEmpty(content);
            ViewBag.FlashMessage = (isEmpty) ? "Micropost cannot be blank!" : "Micropost created!";
            ViewBag.FlashClass = (isEmpty) ? "error" : "success";

            UserModel user = GetUserModelForAuthenticatedUser();
            var micropostsForUser = new MicropostsForUserModel { User = user };
            if (!isEmpty)
            {
                bool saved = _micropostBS.Save(user, content);        
                if (!saved)
                {
                    ViewBag.FlashMessage = "Micropost could not be created!";
                    ViewBag.FlashClass = "error";
                } 
                else
                {
                    user = _userBS.GetUser(user.Id);
                    micropostsForUser = _micropostBS.GetMicropostsForUser(user);
                } 
            }

            return View("Index", micropostsForUser);
        }

        [HttpPost]
        public PartialViewResult Add(string micropostContent)
        {
            UserModel user = GetUserModelForAuthenticatedUser();
            bool isEmpty = string.IsNullOrEmpty(micropostContent);
            if (!isEmpty)
            {
                MicropostModel micropost = _micropostBS.SaveNew(user, micropostContent);
                if (!micropost.Id.IsEmpty())
                {
                    var micropostOwner = new MicropostOwnerModel { Micropost = micropost, Owner = user };
                    return PartialView("_Micropost", micropostOwner);
                }
            }
            return PartialView("_Micropost", new MicropostOwnerModel { Micropost = new MicropostModel(), Owner = user });
        }

        [HttpPost]
        public JsonResult Remove(string userId, string micropostId)
        {
            UserModel user = _userBS.GetUser(new BoRef(userId));
            if (!user.Id.IsEmpty())
            {
                bool deleted = _micropostBS.Delete(user, new BoRef(micropostId));
                if (deleted)
                {
                    return Json("Micropost deleted!"); // View("Index", user); 
                }
            }
            return Json("Micropost could not be deleted!");
        }

        private UserModel GetUserModelForAuthenticatedUser()
        {
            string id = User.Identity.Name;
            return _userBS.GetUser(new BoRef(id));
        }
    }
}

MicropostMVC/Controllers/PagesController.cs
using System.Web.Mvc;

namespace MicropostMVC.Controllers
{
    [AllowAnonymous]
    public class PagesController : Controller
    {
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult Help()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

MicropostMVC/Controllers/SessionsController.cs
using System.Web.Mvc;
using System.Web.Security;
using MicropostMVC.BusinessServices;
using MicropostMVC.Framework.Security;
using MicropostMVC.Models;

namespace MicropostMVC.Controllers
{
    public class SessionsController : Controller
    {
        private readonly IUserBS _userBS;

        public SessionsController(IUserBS userBS)
        {
            _userBS = userBS;
        }

        [HttpGet, AllowAnonymous]
        public ActionResult SignIn()
        {
            string returnUrl = Request.Params[CustomAuthentication.RedirectKey];
            if (!string.IsNullOrEmpty(returnUrl))
            {
                ViewBag.FlashMessage = "Please sign in to access this page.";
                ViewBag.FlashClass = "notice";
                TempData.Add(CustomAuthentication.RedirectKey, returnUrl);
            }
            return View();
        }

        [HttpPost, AllowAnonymous]
        public ActionResult SignIn(UserModel user)
        {
            UserModel userLogged = _userBS.Login(user);
            if (userLogged.Id.IsEmpty())
            {
                ViewBag.FlashMessage = "Invalid email/password combination.";
                ViewBag.FlashClass = "error";
                return View(user);
            }
            
            _userBS.Authenticate(userLogged);
            
            if (TempData.ContainsKey(CustomAuthentication.RedirectKey))
            {
                string returnUrl = TempData[CustomAuthentication.RedirectKey].ToString();
                TempData.Remove(CustomAuthentication.RedirectKey);
                return Redirect(returnUrl);
            }
            return RedirectToAction("Show", "Users", new { id = userLogged.Id.Value });
        }

        public ActionResult SignOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Home", "Pages");
        }
    }
}

MicropostMVC/Views/Shared/_Avatar.cshtml
@using MicropostMVC.Models
@using MicropostMVC.Controllers
@model UserModel

@{
    var avatarPath = UsersController.GetAvatarPath(Model);
    string filePath = Request.MapPath(avatarPath);
    if (!File.Exists(filePath))
    {
        avatarPath = UsersController.GetAvatarPath(new UserModel());
    }

    string classValue = "avatar";
    if (ViewData.ContainsKey("class"))
    {
        classValue = ViewData["class"].ToString();
    }
}
<img id="avatar_@Model.Id.Value"src="@Url.Content(avatarPath)" alt="@Model.Name" class="@classValue"/>
        

MicropostMVC/Views/Shared/_Footer.cshtml
<nav class="round">
    <ul>
        <li>@Html.ActionLink("About", "About", "Pages")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Pages")</li>
        <li><a href="http://www.asp.net/">News</a></li>
        <li><a href="http://www.asp.net/mvc/">MVC</a></li>
    </ul>
</nav>

MicropostMVC/Views/Shared/_Header.cshtml
<img src="@Url.Content("~/Content/images/logo.png")" alt="Microposts .NET MVC" class="round"/>
<nav class="round">
    <ul>
        @if (User.Identity.IsAuthenticated)
        {
            <li>@Html.ActionLink("Home", "Index", "Microposts")</li>
            <li>@Html.ActionLink("Users", "Index", "Users")</li>
            <li>@Html.ActionLink("Settings", "Edit", "Users")</li>
            <li>@Html.ActionLink("Help", "Help", "Pages")</li>
            <li>@Html.ActionLink("Sign out", "SignOut", "Sessions")</li>
        }
        else
        {
            <li>@Html.ActionLink("Home", "Home", "Pages")</li>
            <li>@Html.ActionLink("Help", "Help", "Pages")</li>
            <li>@Html.ActionLink("Sign in", "SignIn", "Sessions")</li>
        }
    </ul>
</nav>
      

MicropostMVC/Views/Shared/_Layout.cshtml
@{
    ViewBag.UrlProject = "https://github.com/marcelopuppin/micropostsmvc";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Microposts .NET MVC</title>
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css")" rel="stylesheet" type="text/css" />
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")" rel="stylesheet" type="text/css" />
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Scripts/js")" type="text/javascript"></script>
<!--
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Scripts/CoffeeScripts/coffee")"></script>
-->
</head>
<body>
    <div class="container">
      <header>
        @RenderPage("_Header.cshtml")
      </header>
      <section class="round">
        @RenderBody()
      </section>
      <footer>
        @RenderPage("_Footer.cshtml")
      </footer>
    </div>
</body>
</html>

MicropostMVC/Views/Shared/_Message.cshtml
@{
    if (ViewBag.FlashMessage == null)
    {
        ViewBag.FlashMessage = "";
    }
    if (ViewBag.FlashClass == null)
    {
        ViewBag.FlashClass = "info";
    }
}
<script type="text/javascript">
    $(window).ready(function () {
        showFlash("@ViewBag.FlashMessage", "@ViewBag.FlashClass");
    });

    var showFlash = function (message, classType) {
        $("#flash").removeClass()
                   .hide();
    
        var visible = (message.length > 0);
        if (visible) {
            $("#flash").html(message)
                       .addClass(classType)
                       .fadeIn(3000);
        }
    };

    var fadeOutFlash = function() {
        $("#flash").fadeOut(2000);
    };
</script>

<!-- flash class: error, alert, notice, success, info -->
<div id="flash" class="@ViewBag.FlashClass" style="display:none" onclick="fadeOutFlash()">
    
</div>

MicropostMVC/Views/Shared/_Micropost.cshtml
@model MicropostMVC.Models.MicropostOwnerModel
@if (!string.IsNullOrEmpty(Model.Micropost.Content))
{
    <tr id="@Model.Micropost.Id.Value">
        <td class="avatar">
            @{
                var data = new ViewDataDictionary {new KeyValuePair<string, object>("class", "avatar-medium")};
                Html.RenderPartial("_Avatar", Model.Owner, data);
            }
        </td>
        <td class="micropost">
            <span class="user">
                @Html.ActionLink(Model.Owner.Name, "Show", "Users", Model.Owner, new {})
            </span>
            <span class="content">@Model.Micropost.Content</span>
            <span class="timestamp">Posted on @Model.Micropost.CreatedAt.ToLocalTime()</span>
        </td>
        <td class="delete">
        @if (User.Identity.Name == Model.Owner.Id.Value)
        {
            <button class="button small greyred" id="deleteMicropost"
                    onclick="confirmDeletion('@Model.Owner.Id','@Model.Micropost.Id.Value');">delete</button>
        } 
        </td>
    </tr>
}

MicropostMVC/Views/Shared/_MicropostAdd.cshtml
<fieldset class="round">
    
    <div class="micropost_new">
        @Html.TextArea("micropostNew")
    </div>

    <p>
        <button class="button large blue" id="Submit" 
                onclick="addMicropost($('#micropostNew').val())">Submit</button>
    </p>

</fieldset>

<script type="text/javascript">
    var addMicropost = function (newMicropost) {
        $('#flash').hide();
        if ($.trim(newMicropost) == '') {
            window.showFlash("Micropost cannot be blank!", "error");
            return;
        }
        $.post('@Url.Action("Add", "Microposts")',
               { micropostContent: newMicropost },
               function (data) {
                   if (data != null) {
                       if ($('#microposts tr').length == 0) {
                           $('#microposts').append(data);
                       } else {
                           $('#microposts tr:first').before(data);
                       }
                       $('#micropostNew').attr("value", "");
                       if (window.userInfoViewModel != null) {
                           window.userInfoViewModel.incrementMicropost();
                       }
                       window.showFlash("Micropost created!", "success");
                       window.fadeOutFlash();
                   } else {
                       window.showFlash("Micropost could not be created!", "error");
                   }
               }
        );
    };

</script>

MicropostMVC/Views/Shared/_MicropostCreate.cshtml
@using (Html.BeginForm("Create","Microposts"))
{
    <fieldset class="round">
    
        <div class="micropost_new">
            @Html.TextArea("micropostNew")
        </div>

        <p>
            <input type="submit" class="button large blue" id="Submit" value="Submit"/>
        </p>

    </fieldset>
}

MicropostMVC/Views/Shared/_MicropostDelete.cshtml
<script type="text/javascript">
    var confirmDeletion = function (user, micropost) {
        $('#flash').hide();
        $('#deleteMessage').dialog(
            {
                modal: true,
                buttons: {
                    No: function () {
                        $(this).dialog("close");
                    },
                    Yes: function () {
                        $(this).dialog("close");
                        $.ajax({
                            type: 'POST',
                            dataType: 'json',  
                            contentType: 'application/json; charset=utf-8',   
                            url: '@Url.Action("Remove", "Microposts")',
                            data: JSON.stringify(SetDataForDeletion(user, micropost)),
                            success: function(data) {
                                $('#' + micropost).remove();
                                if (window.userInfoViewModel != null) {
                                    window.userInfoViewModel.decrementMicropost();
                                }
                                window.showFlash(data, "info");
                                window.fadeOutFlash();
                            },
                            error: function(data) {
                                window.showFlash(data, "error");
                            }
                        });
                    }
                }
            });
    };

    function SetDataForDeletion(user, micropost) {
        return { userId : user, micropostId : micropost };
    }
</script>

<div id="deleteMessage" title="Delete micropost" style="display:none">
    <p>Are you sure?</p>
</div>

MicropostMVC/Views/Shared/_MicropostNew.cshtml
@using (Html.BeginForm("Create","Microposts"))
{
    <fieldset class="round">
    
        <div class="micropost_new">
            @Html.TextArea("micropostNew")
        </div>

        <p>
            <input type="submit" class="button large blue" id="Submit" value="Submit"/>
        </p>

    </fieldset>
}

MicropostMVC/Views/Shared/_Stats.cshtml
@model MicropostMVC.Models.UserModel

<div class="stats">
  <table summary="User stats">
    <tr>
        <td>
            <div class="stat">@Html.ActionLink("Following", "Following", "Users")</div>
            <div class="stat">@Model.Following.Count</div>
        </td>
        <td>
            <div class="stat">@Html.ActionLink("Followers", "Followers", "Users")</div>
            <div class="stat">@Model.Followers.Count</div>
        </td>
    </tr>
  </table>
</div>

MicropostMVC/Views/Shared/_UserInfo.cshtml
@model MicropostMVC.Models.UserModel

<div class="user_info">
    @{
        var data = new ViewDataDictionary {new KeyValuePair<string, object>("class", "avatar-small")};
        Html.RenderPartial("_Avatar", Model, data);
    }
    <span class="user_name">@Model.Name</span>
    <span class="microposts" data-bind="text: totalMicroposts"></span>
    @{
        Html.RenderPartial("_Stats", Model);
    }
</div>

MicropostMVC/Views/Shared/_UserInfoViewModel.cshtml
@model MicropostMVC.Models.UserModel

<script src="@Url.Content("~/Scripts/knockout.js")" type="text/javascript"></script>

<script type="text/javascript">
    var UserInfoViewModel = function(micropostsCount) {
        this.total = ko.observable(micropostsCount);

        this.incrementMicropost = function() {
            this.total(this.total() + 1);
        };
        
        this.decrementMicropost = function() {
            this.total(this.total() - 1);
        };
        
        this.totalMicroposts = ko.computed(function() {
            var text = (this.total() > 1) ? "Microposts" : "Micropost";
            return this.total() + " " + text;
        }, this);
    };

    var userInfoViewModel = new UserInfoViewModel(@Model.Microposts.Count); 
    ko.applyBindings(userInfoViewModel);
   
</script>